apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
    # matchExpressions:
    #   - {key: app, operator: NotIn, values: [second-app, first-app]}
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
        - name: users
          image: ihorshostak/user
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
          imagePullPolicy: Always
#        - name: users
#          image: ihorshostak/auth
#          imagePullPolicy: Always
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8080
#            periodSeconds: 10
#            initialDelaySeconds: 5
        # - name: ...
        #   image: ...
