version: "3.8"

services:
  server:
    platform: linux/amd64
#    image: 'nginx:mainline-alpine'
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    container_name: nginx
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    container_name: mysql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/html
    container_name: composer

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    container_name: artisan
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
    container_name: npm



