apiVersion: v1
kind: PersistentVolume
metadata:
  name: story-vol
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce #- could be used by single node
    #- ReadOnlyMany multiple nodes but read only
    #- ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate