apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-vol-claim
spec:
  volumeName: story-vol
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
